### ISSUE TITLE
Data explorer enhancements - ideas

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#534]
We'll add a list of data explorer enhancements in this issue. When one gets traction, we'll spin off a new, focused and dedicated issue for it. 

**Priorities**:
- [x] Improve How Calculated / Sources display (see `hotfix-measure-metadata`): on all but Table, show only single measure. Problem: when map is initial load, `renderMeasures` runs and shows multiple measures in HC/S boxes. Otherwise, sorted.
- [x] #1003
- [x] Add units in tooltips to better allow people to put values into sentence context (see `hotfix-DE-tooltip`)
- [x] Add a "threshold" data type to support indicators where we have a single value as a measure (like a regulatory threshold or some other reference value). This could perhaps be in `vizOptions` in `indicators.json`, and could be paired with importing it into the page in a variety of places (as a y-value in the trend chart; as a stick-to-top value in the table; in the tooltip on the map?) to add explanation/comparison/context in a strong way. [See gist here](https://gist.github.com/mmontesanonyc/28565345c5c20183e0d29e047e40ae54).
- [ ] Fix issue of trend chart scaling small on mobile view
- [ ] Improve dimensions across the board. 
- [x] Improve trend chart legend labelling
- [x] https://github.com/nychealth/EH-dataportal/issues/1000

**Map**:

- [ ] #97 . 
- [ ] #497 - Min/max on maps? See Restaurants with A Grades - think about showing change over time via maps.
- [ ] Manually override automatic breaks for color scale
- [ ] Vertical line on bar chart to better highlight mouseover neighborhood (esp. when value = 0)
- [x] Rate / Count toggler, with count view showing a bubble map (see #997)
- [x] #616
- [x] Allow turning off geo types (in indicators.json)

**Table**: 
- [x] Refine styles: smaller text; better headers, colors, and ledger lines; render a column as a bar charT?
- [x] "Select All" button for years

**Links**

- [ ] Incorporate [ICE with Disparities view](https://github.com/nychealth/EH-dataportal/issues/862)
- [ ] #106 
- [x] Button-out the drop-down menu? Or some other way that people can see all the potentially connected things?
- [x] Distinguish overlapping points

**Trend**

- [x] #840
- [ ] Click on group point or legend highlights that group (like links chart) 
- [x] Show missing years as explicitly missing. Using `end_period` for x-axis field, but `TimePeriod` for label won't work, because `labelExpr` doesn't have access to anything but the name and value of the `field`. **One alternative**: finding missing sequence values in `renderComparisonsChart` and adding them to the data. **Another alternative**: using `end_period`, but conditionally modifying the `timeUnit` or `format` in `renderComparisonsChart` to recreate `TimePeriod`. This is probably the better option.

**Disparities**

- [ ] ICE score
- [ ] TRIE neighborhoods,

**General**
- [ ] When views are inactive (e.g., no map, no trend), explain rationale: eg, "We don't map things if we don't have data finer than RESOLUTION."
- [ ] See asthma - use "label" for indicator menu if Indicator header exists?
- [ ] Data updated time, using git log on EHDP-data repo
- [ ] Database rebuild - add facets: age. sex. other?

**Data Explorer Drill-down**
Add some type of interpretation - something that helps answer The Why.  
- Perhaps a "what does this chart mean" 
-  Something customized and specced at the indicator level where we link to the top resources on the portal instead of relying on the Related footer
- A threshold value; an interpretative sentence for a chosen neighborhood that compares the value to the NYC average. 

**Console logs**: Revise console logs to be descriptive. Log the relevant objects, specific selections. Partly, this can be useful for us (easier to find the names of objects), and partly, useful to any techie poking around.

**Comment by mmontesanonyc** [comment]
NB, consolidated with other "Ideas" card. FYI, Mike had some thoughts (added here) about adding some type of "Data Explorer Drill-down" functionality that gets into ways to explain what a user is seeing. Touches on a lot of ideas we had - and definitely an interesting area for growth.

**Comment by mmontesanonyc** [comment]
@cgettings related to WM's point about legend labels not wrapping. I've been interested for a while in applying direct labels to trend charts, instead of legends. Here's an initial - there's a layer that takes the max date, the value at the max date, and then encodes a text mark there. The major drawback is interference, but I'm going to look into the [label transform](https://vega.github.io/vega/docs/transforms/label/) and `avoidMarks` to see what can be accomplished with that.

**Comment by mmontesanonyc** [comment]
Adding an idea in here: hiding a menu sidebar control when there is only one option within it.

**Comment by mmontesanonyc** [comment]
@cgettings an idea in `feature-mapbar-hover`. A rule and text mark that appear on hover. But, for the largest value, it messes with the chart dimensions. I tried assigning a scale domain to 1.2 * max Value, but couldn't do that inside vega-lite. And, I also tried a conditional on text.align, but that didn't work, unfortunately. Might just let this linger as an idea.

**Comment by mmontesanonyc** [comment]
FYI all: on `feature-de-bar-with-ci`, i added another condition to map.js that identifies when the data has CIs, and revises the barChart spec accordingly. You can test this out on some of the asthma indicators (adults with asthma for example).  

Two slight drawbacks:
- For a few of the indicators (eg Children Ever Diagnosed With Asthma), they're by NHAC: very few geographies, so, few entries in the bar chart. Small dots compared to the width of the bars. Not sure if there's anything to be done about that or if it's just an edge case to deal with. 
- Smallish dots have low contrast against the bars down in the yellow range; I revised the stroke around the dot to try to separate the two visually. (@etorem you may have thoughts here?)

Otherwise, I think this is a nice enhancement. Thoughts, all?

Would love if @cgettings and @JackGoldsmith can do a little bit of QC to make sure there aren't any unexpected consequences.

<img width="861" height="865" alt="Image" src="https://github.com/user-attachments/assets/07ef115b-4a90-4be7-8efb-ca7dffe6d4cb" />

**Comment by mmontesanonyc** [comment]
One other thing we could do is change the highlight, too, to highlight the CI bar instead of the dot.

**Comment by mmontesanonyc** [comment]
FYI on `feature-DE-label-final` - I'm testing a `trend.js` solution that has label-final-value, with an offset to help eliminate clustering/stacking of the final label - in the image below you can see that the borough labels are spread out proportional to the final values. This looks at all the final values, finds the median, keeps that relatively un-offset, and then offsets the labels above and below it...

I have a few more approaches I can incorporate to help de-cluster some ones with more substantial overlap, tho there are some indicators (childhood lead) that really just won't work. 

Eager to QC this across more indicators and ry to get to direct labels and away from legends; this also may require some fiddling with other aspects of the code (legends on mobile, etc). 

<img width="769" height="565" alt="Image" src="https://github.com/user-attachments/assets/c23e5c68-86e3-40e0-bb40-168f36080eff" />

**Comment by mmontesanonyc** [comment]
To recap: I want to remove legends, and label the final value with the series name; when one chart spec is fed by many indicators, you will get label overlap, and people will not like this. So, wanted to write a label-deoverlapping approach.

This is tricky! A few things that need to happen in this process:
- First, we have to grab the y-axis-range - we can use the `max chart value` as a proxy for that. 
- Then, we set a percentage of `max chart value` that constitutes a label collision.
- Then, we move up a label if there's a collision. My initial approach was to create a dy (y-offset) value if there's a collision, but I chose to use the `encoding.y` instead of `dy`. 

That works pretty well, but what if there's a collision between the next value, and the moved value? So we essentially have to go through this a few times, looking for collisions with each new value, and nudging things accordingly.

Then, after all of that, I offset below the lowest value, which helps spread things out when there are collisions. 

There may be better ways, too, but this is working pretty good.

NB @cgettings and also fyi @mmueller1-NYCDOHMH - this approach can definitely be used in other projects, and mostly involves creating transforms in the spec to do some in-spec calculations. 

<img width="1014" height="817" alt="Image" src="https://github.com/user-attachments/assets/c762e6f6-d45c-454f-b1eb-2be60d463e08" />

**Comment by mmontesanonyc** [comment]
@cgettings, on `feature-print-resizer` I have a way to resize the charts in the "Save chart" (print) modal, but it fails for the map. Not sure why. 

Briefly - when a chart is drawn, it saves the spec to "printSpec"; when somebody opens "Save Chart" it runs print.js, modifies the spec a little bit, and draws it in the modal (with source info, etc). I tried to add `resize: horizontal` so that somebody can change the dimensions of the chart, but, it winds up doing funky stuff to the map (and only the map). May leave it for a bit, but if you can take a look and refine, that'd be great. 

edit: this seems to be working now!

**Comment by mmontesanonyc** [comment]
Secretly, one of the things that bugs the heck outta me is that the y-axis and x-axis labels have different font sizes.

On the y-axis, we keep the larger one for consistency across chart types (indicator name large, measurement/display type smaller). But we can't have two-level styling on the x-axis label. 

<img width="813" height="678" alt="Image" src="https://github.com/user-attachments/assets/65708472-c7e5-4b40-a6d8-530c13e1c4a3" />

**Comment by mmontesanonyc** [comment]
Remove 0s from bar charts with maps, by adding this to `encoding.y.axis`:

```
"labelExpr": "(isObject(datum) ? datum.value : datum) === 0 ? '' : (isObject(datum) ? datum.value : datum)"
```

**Comment by mmontesanonyc** [comment]
@etorem @JackGoldsmith, on the branch `hotfix-DE-bar-label`, I've added an expression for the DE map/bar charts that makes it so that the 0 y-axis label isn't shown. Can you please add some QC eyeballs? Click through a few indicators and make sure there are no funky display issues? TY!

**Comment by etorem** [comment]
@mmontesanonyc you decided you were going to maybe experiment with this a bit more before proceeding right?

**Comment by mmontesanonyc** [comment]
> [@mmontesanonyc](https://github.com/mmontesanonyc) you decided you were going to maybe experiment with this a bit more before proceeding right?

Yes, TY. Dropping the 0 is weird when we have the dots with CIs - they're just floating in space. Maybe a firmer x-axis line - or maybe it needs the 0.
